# SAP BW transformation 0KWDLDTX68KXWWP5UN8F1X1A7FVMHRJC
# ZTRAN_EKKO_HIST -> /IMO/PUR_D10
# Destination: Databricks / PySpark
# Generated by: openai (o3)
# Validation: passed
# Review before running against real data.
# FIELD ROUTINE ZCOURREF: upper-case UNSEZ, remove disallowed chars, collapse spaces, trim
# FIELD ROUTINE ZCYOURREF: upper-case IHREZ, remove disallowed chars, collapse spaces, trim
# FIELD ROUTINE ZHDRTEXT: upper-case ZZHDRTXT, remove disallowed chars, collapse spaces, trim
# EXTERNAL TABLES:
# ASSUMPTIONS: Allowed characters are A–Z, 0–9, '_', '/', '-' and space; others are replaced with space. 0RECORDMODE constant is the empty string.
from pyspark.sql import functions as F

def start_routine(df):
    # No start routine logic defined in ABAP
    return df

def lookups(df):
    # No look-ups in the ABAP code
    return df

def derive_fields(df):
    # Common cleaning expression matching the ABAP character loop
    allowed_pattern = "[^A-Z0-9_/\\-]"  # everything NOT allowed

    df = (
        df
        # Direct mappings
        .withColumn("`0COMP_CODE`", F.col("BUKRS"))
        .withColumn("`0OI_EBELN`", F.col("EBELN"))
        # Routine: ZCOURREF
        .withColumn(
            "ZCOURREF",
            F.trim(
                F.regexp_replace(
                    F.regexp_replace(F.upper(F.col("UNSEZ")), allowed_pattern, " "),
                    "\\s+",
                    " "
                )
            ),
        )
        # Routine: ZCYOURREF
        .withColumn(
            "ZCYOURREF",
            F.trim(
                F.regexp_replace(
                    F.regexp_replace(F.upper(F.col("IHREZ")), allowed_pattern, " "),
                    "\\s+",
                    " "
                )
            ),
        )
        # Routine: ZHDRTEXT
        .withColumn(
            "ZHDRTEXT",
            F.trim(
                F.regexp_replace(
                    F.regexp_replace(F.upper(F.col("ZZHDRTXT")), allowed_pattern, " "),
                    "\\s+",
                    " "
                )
            ),
        )
        # Constant mapping
        .withColumn("`0RECORDMODE`", F.lit(""))
    )
    return df

def final_projection(df):
    return df.select(
        "`0RECORDMODE`",
        "`0COMP_CODE`",
        "`0OI_EBELN`",
        "ZCOURREF",
        "ZCYOURREF",
        "ZHDRTEXT"
    )

def transform(src):
    df = start_routine(src)
    df = lookups(df)
    df = derive_fields(df)
    df = final_projection(df)
    return df
