# SAP BW transformation 0KWDLDTX68KXWWP5UN8F1X1A7FVMHRJC
# ZTRAN_EKKO_HIST -> /IMO/PUR_D10
# Destination: Databricks / PySpark
# Generated by: openai (o3)
# Validation: passed
# Review before running against real data.
# FIELD ROUTINE ZCOURREF : upper-case UNSEZ and replace characters outside A–Z, 0–9, space, _ . / - with space
# FIELD ROUTINE ZCYOURREF : upper-case IHREZ and replace characters outside A–Z, 0–9, space, _ . / - with space
# FIELD ROUTINE ZHDRTEXT  : upper-case ZZHDRTXT and replace characters outside A–Z, 0–9, space, _ . / - with space
# ASSUMPTIONS:
#   - 0RECORDMODE is mapped as constant empty string because the workbook lists no value.
#   - BW-allowed character set approximated as: A–Z, 0–9, space, underscore, hyphen, dot, and slash.
from pyspark.sql import functions as F

# ----------------------------------------------------------------------
def start_routine(df):
    # No START routine logic in the ABAP source
    return df


# ----------------------------------------------------------------------
def lookups(df):
    # No look-up tables referenced by the ABAP source
    return df


# ----------------------------------------------------------------------
def derive_fields(df):
    """
    Derive constant, direct and routine-based target columns.
    """

    def clean_bw_char(col_expr):
        """
        Implements the character-by-character check performed in the ABAP
        routines via RSKC_CHAVL_CHECK.

        1. Upper-case the string.
        2. Replace any character not in the allowed set with a space.
        """
        allowed_regex = r"[^A-Z0-9 ./_-]"
        return F.regexp_replace(F.upper(col_expr), allowed_regex, " ")

    df_enriched = (
        df
        # Constant mapping
        .withColumn("0RECORDMODE", F.lit(""))
        # Direct mappings
        .withColumn("0COMP_CODE", F.col("BUKRS"))
        .withColumn("0OI_EBELN", F.col("EBELN"))
        # FIELD ROUTINES
        .withColumn("ZCOURREF", clean_bw_char(F.col("UNSEZ")))
        .withColumn("ZCYOURREF", clean_bw_char(F.col("IHREZ")))
        .withColumn("ZHDRTEXT", clean_bw_char(F.col("ZZHDRTXT")))
    )

    return df_enriched


# ----------------------------------------------------------------------
def final_projection(df):
    """
    Select target columns in their final order.
    """
    target_cols = [
        "0RECORDMODE",
        "0COMP_CODE",
        "0OI_EBELN",
        "ZCOURREF",
        "ZCYOURREF",
        "ZHDRTEXT",
    ]
    return df.select(*[F.col(c) for c in target_cols])


# ----------------------------------------------------------------------
def transform(src):
    """
    Entry point mirroring BW transformation flow:
    start routine  -> lookups -> derive fields -> final projection
    """
    df = start_routine(src)
    df = lookups(df)
    df = derive_fields(df)
    df = final_projection(df)
    return df
